---
- name: Deploy Docker Compose stack
  hosts: all
  become: true

  tasks:
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Pull Backend Image
      docker_image:
        name: hyndhu/backend
        source: pull

    - name: Pull Frontend Image
      docker_image:
        name: hyndhu/frontend
        source: pull

    - name: Copy Docker Compose file to host
      copy:
        src: /var/lib/jenkins/workspace/test_project/docker-compose.yaml
        dest: /docker-compose.yaml

    - name: Start Docker Compose stack
      command: docker-compose up -d
      args:
        chdir: /